### ISSUE TITLE
MLBStats importing error

### ISSUE THREAD

**Issue by tscheer100** [davidbegin/python-in-the-morning#14]
the goal of my issue I'm having is to run another script from within a main script (in this case, AL_BattingStats from AL_AllStats

AL_BattingStats works properly when running correctly (read the comments at the bottom of the script), however, I'm getting a massive error when I run it from AL_AllStats

https://github.com/tscheer100/MLBStats

```
C:\Users\Turtle\AppData\Local\Programs\Python\Python37\python.exe C:/Users/Turtle/PycharmProjects/MLBStats/AL_AllStats.py
Traceback (most recent call last):
  File "C:/Users/Turtle/PycharmProjects/MLBStats/AL_AllStats.py", line 1, in <module>
    from AL import AL_BattingStats
  File "C:\Users\Turtle\PycharmProjects\MLBStats\AL\AL_BattingStats.py", line 30, in <module>
    HeaderData()
  File "C:\Users\Turtle\PycharmProjects\MLBStats\AL\AL_BattingStats.py", line 28, in HeaderData
    with open(os.path.join(os.getcwd(), 'Data\AL_Batting_Stats.txt'), 'w') as r:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Turtle\\PycharmProjects\\MLBStats\\Data\\AL_Batting_Stats.txt'
The current working directory is C:\Users\Turtle\PycharmProjects\MLBStats
```

I assume it's because I still do not understand __main__.py and __init__.py

**Comment by McCroden** [comment]
> I'm getting a massive error when

When what?

**Comment by tscheer100** [comment]
> > I'm getting a massive error when
> 
> When what?

derp. updated it

**Comment by McCroden** [comment]
@tscheer100 did you read the error? most of the helpful bits are usually the last few lines. 

Your folder path is wrong. 3rd line from the end.

**Comment by tscheer100** [comment]
I added a debugger to AL_AllStats to find out what the cwd is seen here:
```
pathName = os.getcwd()
print("The current working directory is %s" % pathName)
```
the results:
AL_BattingStats
"The current working directory is C:\Users\Turtle\PycharmProjects\MLBStats\AL"
AL_AllStats
"The current working directory is C:\Users\Turtle\PycharmProjects\MLBStats"

to fix the issue I changed up the directories method some

```
def directories():
    if pathName == r"C:\Users\Turtle\PycharmProjects\MLBStats\AL":
        if os.path.isdir('.\Data'):
            with open(os.path.join(os.getcwd(), 'Data\AL_Batting_Stats.txt'), "w") as r:
                r.write("check passed")
            print("File created in the AL\Data folder")
        else:
            try:
                os.mkdir('.\Data')
            except Exception as e:
                print("[FATAL ERROR]", e)
            else:
                with open(os.path.join(os.getcwd(), '\Data\AL_Batting_Stats.txt'), "w") as r:
                    r.write("check passed")
                print("File created in the AL\Data folder")
    else:
        if os.path.isdir('.\AL\Data'):
            with open(os.path.join(os.getcwd(), 'AL\Data\AL_Batting_Stats.txt'), "w") as r:
                r.write("check passed")
            print("File created in the AL\Data folder")
        else:
            try:
                os.mkdir('.\AL\Data')
            except Exception as e:
                print("[FATAL ERROR]", e)
            else:
                with open(os.path.join(os.getcwd(), 'AL\Data\AL_Batting_Stats.txt'), "w") as r:
                    r.write("check passed")
                print("File created in the AL\Data folder")

directories()

```

**Comment by McCroden** [comment]
Is the issue resolved?

**Comment by McCroden** [comment]
@tscheer100 You should mark this issue as closed.
